name: Hive Guard Protection

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: contriboss/hive-guard-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
