name: Swarm Shield Protection

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: contriboss/swarm-shield-action@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
