name: Run Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', '3.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run Rake Task
        run: bundle exec rake

      - name: Upload Capistrano log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capistrano-log-${{ matrix.ruby-version }}
          path: test/log/*.log
